name: ANLY520
channels:
  - conda-forge
  - pyviz/label/dev
dependencies:
  - jupyterlab
  - pandas
  - nltk
  - pyviz
  - r
  - mro-base #r-base
  - r-essentials
  - r-irkernel
  - rpy2
  - wordcloud
  - pip:
    - jupyterlab_latex
