name: ANLY520
channels:
  - conda-forge
  - pyviz/label/dev
  - r
dependencies:
  - jupyterlab
  - libgfortran
  - simplegeneric
  - pandas
  - nltk
  - pyviz
  - r
  - r-base #mro-base
  - r-essentials
  - r-irkernel
  - r-tidyverse
  - r-reticulate
  - r-rtweet
  - rpy2
  - wordcloud
  - pip:
    - jupyterlab_latex
